In [10]:
import h5py
import numpy as np
import os, sys
import pandas as pd
sys.path.append(os.path.abspath("../data/MillionSongSubset"))
import tables
import sqlite3
import pandas as pd
from pathlib import Path
from pprint import pprint

In [3]:
# Update this path if your file is elsewhere
db_path = Path("/Users/pushpita/Documents/ML_Projects/echoagent/data/bow/bow.db")

conn = sqlite3.connect(db_path)
print("Connected to:", db_path.resolve())

Connected to: /Users/pushpita/Documents/ML_Projects/echoagent/data/bow/bow.db

In [4]:
# List tables
tables = pd.read_sql_query("""
SELECT name, type
FROM sqlite_master
WHERE type IN ('table', 'view')
ORDER BY name
""", conn)

tables

Empty DataFrame
Columns: [name, type]
Index: []

In [5]:
# Show schema for each table
for t in tables["name"]:
    print(f"\n=== {t} ===")
    display(pd.read_sql_query(f"PRAGMA table_info({t})", conn))

In [6]:
# Row counts for each table
counts = []
for t in tables["name"]:
    n = pd.read_sql_query(f"SELECT COUNT(*) AS n FROM {t}", conn).iloc[0]["n"]
    counts.append({"table": t, "rows": n})

pd.DataFrame(counts)

Empty DataFrame
Columns: []
Index: []

In [7]:
# Preview rows (works for the MXM sqlite built by mxm_dataset_to_db.py: words + lyrics)
for t in tables["name"]:
    print(f"\n=== Preview: {t} ===")
    display(pd.read_sql_query(f"SELECT * FROM {t} LIMIT 20", conn))

In [ ]:
# How many unique tracks / words / lyric rows?
pd.read_sql_query("""
SELECT
  (SELECT COUNT(*) FROM words) AS n_words,
  (SELECT COUNT(*) FROM lyrics) AS n_lyrics_rows,
  (SELECT COUNT(DISTINCT track_id) FROM lyrics) AS n_tracks
""", conn)

In [9]:
sys.path.append(os.path.abspath("../"))
from backend.data.embeddings import EmbeddingManager

mgr = EmbeddingManager()  # uses /Users/pushpita/Documents/ML Projects/echoagent/backend/data/chroma_db

print("track_text count:", mgr.track_collection.count())
print("lyrics count:", mgr.lyrics_collection.count())
print("peek:", mgr.track_collection.peek(limit=3))

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1773653073.318952 7506421 instrument.cc:563] Metric with name 'grpc.resource_quota.calls_dropped' registered more than once. Ignoring later registration.
E0000 00:00:1773653073.318978 7506421 instrument.cc:563] Metric with name 'grpc.resource_quota.calls_rejected' registered more than once. Ignoring later registration.
E0000 00:00:1773653073.318980 7506421 instrument.cc:563] Metric with name 'grpc.resource_quota.connections_dropped' registered more than once. Ignoring later registration.
E0000 00:00:1773653073.318981 7506421 instrument.cc:563] Metric with name 'grpc.resource_quota.instantaneous_memory_pressure' registered more than once. Ignoring later registration.
E0000 00:00:1773653073.318983 7506421 instrument.cc:563] Metric with name 'grpc.resource_quota.memory_pressure_control_value' registered more than once. Ignoring later registration.

track_text count: 2350
lyrics count: 0
peek: {'ids': ['TRAAABD128F429CF47', 'TRAAAEF128F4273421', 'TRAAAFD128F92F423A'], 'embeddings': array([[-0.05046621, -0.09049937,  0.03075439, ...,  0.01763589,
        -0.01323299, -0.09263226],
       [-0.05862552, -0.06566019,  0.07236075, ..., -0.05565469,
        -0.0189395 , -0.11603994],
       [ 0.0065825 , -0.00648657,  0.01445311, ..., -0.05940343,
         0.03519609, -0.10818638]], shape=(3, 384)), 'documents': [None, None, None], 'uris': None, 'included': ['metadatas', 'documents', 'embeddings'], 'data': None, 'metadatas': [{'genres_csv': 'oldies', 'song_id': 'TRAAABD128F429CF47', 'tag_source': 'msd_lastfm_map', 'msd_track_id': 'TRAAABD128F429CF47', 'tags_csv': '60s|soul|pop|rock|malevocalists|oldies|1969', 'track_id': 'TRAAABD128F429CF47', 'lyrics_source': 'mxm', 'has_lyrics': False, 'has_bow': True, 'genre_source': 'msd_lastfm_map', 'mxm_tid': '6477168'}, {'mxm_tid': '3759847', 'track_id': 'TRAAAEF128F4273421', 'genre_source': 'msd_lastfm_map', 'has_lyrics': False, 'lyrics_source': 'mxm', 'tag_source': 'msd_lastfm_map', 'has_bow': True, 'genres_csv': 'rock', 'msd_track_id': 'TRAAAEF128F4273421', 'tags_csv': 'newwave|80s|freedom|strangeromanticdeadrockcave', 'song_id': 'TRAAAEF128F4273421'}, {'song_id': 'TRAAAFD128F92F423A', 'tag_source': 'msd_lastfm_map', 'track_id': 'TRAAAFD128F92F423A', 'mxm_tid': '6640025', 'has_bow': True, 'lyrics_source': 'mxm', 'genres_csv': 'rock', 'tags_csv': 'punkrock|punk', 'msd_track_id': 'TRAAAFD128F92F423A', 'genre_source': 'msd_lastfm_map', 'has_lyrics': False}]}

In [8]:
results = mgr.query_track_embeddings("rock")
for r in results[:5]:
    print(r["id"], r["distance"], r["metadata"])

In [26]:
sample = mgr.track_collection.peek(limit=5)
sample["metadatas"]

Failed to send telemetry event CollectionGetEvent: capture() takes 1 positional argument but 3 were given

[{'genre_source': 'msd_lastfm_map',
  'genres_csv': 'oldies',
  'has_bow': True,
  'has_lyrics': False,
  'lyrics_source': 'mxm',
  'msd_track_id': 'TRAAABD128F429CF47',
  'mxm_tid': '6477168',
  'song_id': 'TRAAABD128F429CF47',
  'tag_source': 'msd_lastfm_map',
  'tags_csv': '60s|soul|pop|rock|malevocalists|oldies|1969',
  'track_id': 'TRAAABD128F429CF47'},
 {'genre_source': 'msd_lastfm_map',
  'genres_csv': 'jazz',
  'has_bow': True,
  'has_lyrics': False,
  'lyrics_source': 'mxm',
  'msd_track_id': 'TRAAAED128E0783FAB',
  'mxm_tid': '2516445',
  'song_id': 'TRAAAED128E0783FAB',
  'tag_source': 'msd_lastfm_map',
  'tags_csv': 'jazz|jamiecullum|singersongwriter|other|piano',
  'track_id': 'TRAAAED128E0783FAB'},
 {'genre_source': 'msd_lastfm_map',
  'genres_csv': 'rock',
  'has_bow': True,
  'has_lyrics': False,
  'lyrics_source': 'mxm',
  'msd_track_id': 'TRAAAEF128F4273421',
  'mxm_tid': '3759847',
  'song_id': 'TRAAAEF128F4273421',
  'tag_source': 'msd_lastfm_map',
  'tags_csv': 'newwave|80s|freedom|strangeromanticdeadrockcave',
  'track_id': 'TRAAAEF128F4273421'},
 {'genre_source': 'msd_lastfm_map',
  'genres_csv': 'rock',
  'has_bow': True,
  'has_lyrics': False,
  'lyrics_source': 'mxm',
  'msd_track_id': 'TRAAAFD128F92F423A',
  'mxm_tid': '6640025',
  'song_id': 'TRAAAFD128F92F423A',
  'tag_source': 'msd_lastfm_map',
  'tags_csv': 'punkrock|punk',
  'track_id': 'TRAAAFD128F92F423A'},
 {'genre_source': 'msd_lastfm_map',
  'genres_csv': 'pop',
  'has_bow': True,
  'has_lyrics': False,
  'lyrics_source': 'mxm',
  'msd_track_id': 'TRAAAGF12903CEC202',
  'mxm_tid': '5493388',
  'song_id': 'TRAAAGF12903CEC202',
  'tag_source': 'msd_lastfm_map',
  'tags_csv': 'ballad|norwegian|lovesong',
  'track_id': 'TRAAAGF12903CEC202'}]

In [12]:

print("track_text count:", mgr.track_collection.count())
print("lyrics count:", mgr.lyrics_collection.count())

print("\nTrack peek:")
print(mgr.track_collection.peek(limit=5))

print("\nLyrics peek:")
print(mgr.lyrics_collection.peek(limit=5))

track_text count: 100
lyrics count: 0

Track peek:
{'ids': ['TRAAABD128F429CF47', 'TRAAAED128E0783FAB', 'TRAAAEF128F4273421', 'TRAAAFD128F92F423A', 'TRAAAGF12903CEC202'], 'embeddings': array([[-0.05046621, -0.09049937,  0.03075439, ...,  0.01763589,
        -0.01323299, -0.09263226],
       [-0.0031452 , -0.13569978,  0.01060263, ..., -0.01617149,
        -0.08005787, -0.08536361],
       [-0.05862552, -0.06566019,  0.07236075, ..., -0.05565469,
        -0.0189395 , -0.11603994],
       [ 0.0065825 , -0.00648657,  0.01445311, ..., -0.05940343,
         0.03519609, -0.10818638],
       [-0.01723531, -0.04160674,  0.03166847, ..., -0.00258316,
         0.02371109, -0.05335718]], shape=(5, 384)), 'documents': [None, None, None, None, None], 'uris': None, 'included': ['metadatas', 'documents', 'embeddings'], 'data': None, 'metadatas': [{'genres_csv': 'oldies', 'tag_source': 'msd_lastfm_map', 'lyrics_source': 'mxm', 'mxm_tid': '6477168', 'genre_source': 'msd_lastfm_map', 'tags_csv': '60s|soul|pop|rock|malevocalists|oldies|1969', 'track_id': 'TRAAABD128F429CF47', 'has_bow': True, 'msd_track_id': 'TRAAABD128F429CF47', 'has_lyrics': False, 'song_id': 'TRAAABD128F429CF47'}, {'has_bow': True, 'mxm_tid': '2516445', 'genre_source': 'msd_lastfm_map', 'has_lyrics': False, 'track_id': 'TRAAAED128E0783FAB', 'tags_csv': 'jazz|jamiecullum|singersongwriter|other|piano', 'lyrics_source': 'mxm', 'tag_source': 'msd_lastfm_map', 'msd_track_id': 'TRAAAED128E0783FAB', 'song_id': 'TRAAAED128E0783FAB', 'genres_csv': 'jazz'}, {'tag_source': 'msd_lastfm_map', 'genre_source': 'msd_lastfm_map', 'song_id': 'TRAAAEF128F4273421', 'track_id': 'TRAAAEF128F4273421', 'has_lyrics': False, 'msd_track_id': 'TRAAAEF128F4273421', 'tags_csv': 'newwave|80s|freedom|strangeromanticdeadrockcave', 'mxm_tid': '3759847', 'genres_csv': 'rock', 'lyrics_source': 'mxm', 'has_bow': True}, {'has_lyrics': False, 'genres_csv': 'rock', 'tag_source': 'msd_lastfm_map', 'lyrics_source': 'mxm', 'tags_csv': 'punkrock|punk', 'genre_source': 'msd_lastfm_map', 'msd_track_id': 'TRAAAFD128F92F423A', 'mxm_tid': '6640025', 'track_id': 'TRAAAFD128F92F423A', 'has_bow': True, 'song_id': 'TRAAAFD128F92F423A'}, {'track_id': 'TRAAAGF12903CEC202', 'lyrics_source': 'mxm', 'tags_csv': 'ballad|norwegian|lovesong', 'genre_source': 'msd_lastfm_map', 'mxm_tid': '5493388', 'song_id': 'TRAAAGF12903CEC202', 'has_lyrics': False, 'msd_track_id': 'TRAAAGF12903CEC202', 'tag_source': 'msd_lastfm_map', 'has_bow': True, 'genres_csv': 'pop'}]}

Lyrics peek:
{'ids': [], 'embeddings': array([], dtype=float64), 'documents': [], 'uris': None, 'included': ['metadatas', 'documents', 'embeddings'], 'data': None, 'metadatas': []}

In [17]:
import pandas as pd
from backend.data.embeddings import EmbeddingManager

manager = EmbeddingManager()

rows = manager.track_collection.get(
    limit=100,
    include=["metadatas"]
)

df = pd.DataFrame(rows["metadatas"])
df.insert(0, "id", rows["ids"])

df.head(10)

,id,has_bow,tag_source,genres_csv,tags_csv,track_id,msd_track_id,has_lyrics,genre_source,mxm_tid,song_id,lyrics_source
0,TRAAABD128F429CF47,True,msd_lastfm_map,oldies,60s|soul|pop|rock|malevocalists|oldies|1969,TRAAABD128F429CF47,TRAAABD128F429CF47,False,msd_lastfm_map,6477168,TRAAABD128F429CF47,mxm
1,TRAAAEF128F4273421,True,msd_lastfm_map,rock,newwave|80s|freedom|strangeromanticdeadrockcave,TRAAAEF128F4273421,TRAAAEF128F4273421,False,msd_lastfm_map,3759847,TRAAAEF128F4273421,mxm
2,TRAAAFD128F92F423A,True,msd_lastfm_map,rock,punkrock|punk,TRAAAFD128F92F423A,TRAAAFD128F92F423A,False,msd_lastfm_map,6640025,TRAAAFD128F92F423A,mxm
3,TRAAARJ128F9320760,True,msd_lastfm_map,rock,progressiverock|progrock|bra2|titletracks,TRAAARJ128F9320760,TRAAARJ128F9320760,False,msd_lastfm_map,1422131,TRAAARJ128F9320760,mxm
4,TRAABJV128F1460C49,True,msd_lastfm_map,slowhand,slowhand|videokilledtheradiostar,TRAABJV128F1460C49,TRAABJV128F1460C49,False,msd_lastfm_map,851082,TRAABJV128F1460C49,mxm
5,TRAABLR128F423B7E3,True,msd_lastfm_map,rock,classicrock|canadian|country|blues|singersongw...,TRAABLR128F423B7E3,TRAABLR128F423B7E3,False,msd_lastfm_map,1094747,TRAABLR128F423B7E3,mxm
6,TRAABVM128F92CA9DC,True,msd_lastfm_map,rock,hardrock|rock|tesla|classicrock|love|chillout|...,TRAABVM128F92CA9DC,TRAABVM128F92CA9DC,False,msd_lastfm_map,2097569,TRAABVM128F92CA9DC,mxm
7,TRAACER128F4290F96,True,msd_lastfm_map,hardcore,mathcore|hardcore|experimental|metalcore|metal,TRAACER128F4290F96,TRAACER128F4290F96,False,msd_lastfm_map,8700148,TRAACER128F4290F96,mxm
8,TRAACFV128F935E50B,True,msd_lastfm_map,oldies,oldies|60sgirls|femalevocalist|memories|gh10|m...,TRAACFV128F935E50B,TRAACFV128F935E50B,False,msd_lastfm_map,7859229,TRAACFV128F935E50B,mxm
9,TRAACHN128F1489601,True,msd_lastfm_map,metal,metal|lie|thefavouritestsong,TRAACHN128F1489601,TRAACHN128F1489601,False,msd_lastfm_map,4168849,TRAACHN128F1489601,mxm